export const NAV = {
  HOME: "HOME",
  ABOUT_US: "ABOUT_US",
  MEMBERS: "MEMBERS",
  SCHEDULE: "SCHEDULE",
  MEETUPS: "MEETUPS",
  ARCHIVE: "ARCHIVE",
  BOARD: "BOARD",
  SIGN_UP: "SIGN_UP",
  LOGOUT: "LOGOUT",
};
