export const NAV = {
  HOME: "HOME",
  ABOUT_US: "ABOUT US",
  MEMBERS: "MEMBERS",
  SCHEDULE: "SCHEDULE",
  MEETUPS: "MEETUPS",
  ARCHIVE: "ARCHIVE",
  BOARD: "BOARD",
  SIGN_UP: "SIGN UP",
  SIGN_OUT: "SIGN OUT",

  HEADER_HEIGHT: "95px",
};
